name: "KidayPisun"
version: ${project.version}

main: com.github.groundbreakingmc.kidaypisun.KidayPisun
api-version: 1.16

author: GroundbreakingMC

commands:
  pisun:
    permission: kidaypisun.use
    aliases: [spampisun]